name: RawNet2
n_gpu: 1
preprocessing:
  sr: 16000
  time_target: 4
arch:
  _target_: src.model.RawNet2
  sinc_filter_length: 1024
  sinc_channels: 20
  inverse_mel: false
  min_low_hz: 0
  min_band_hz: 0
  abs_after_sinc: true
  block1_channels: 20
  block1_num_layers: 2
  block2_channels: 128
  block2_num_layers: 4
  gru_hidden: 1024
  gru_num_layers: 3
  fc_hidden: 1024
data:
  train:
    batch_size: 32
    num_workers: 5
    datasets:
      train:
        _target_: src.datasets.ASVDataset
        part: "train"
  val:
    batch_size: 32
    num_workers: 5
    datasets: 
      test:
        _target_: src.datasets.ASVDataset
        part: "eval"
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
  weight_decay: 1e-4
loss:
  _target_: src.loss.RawNet2Loss
  bonafide_weight: 9.0 
  spoof_weight: 1.0
metrics:

lr_scheduler:

trainer:
  epochs: 50
  save_dir: "saved/"
  save_period: 5
  verbosity: 2
  monitor: "min train_loss"
  early_stop: 200
  visualize: "wandb"
  wandb_project: "as_project"
  grad_norm_clip: 10
